python -B test_SemanticKITTI.py --test_area 11
python -B test_SemanticKITTI.py --test_area 12
python -B test_SemanticKITTI.py --test_area 13
python -B test_SemanticKITTI.py --test_area 14
python -B test_SemanticKITTI.py --test_area 15
python -B test_SemanticKITTI.py --test_area 16
python -B test_SemanticKITTI.py --test_area 17
python -B test_SemanticKITTI.py --test_area 18
python -B test_SemanticKITTI.py --test_area 19
python -B test_SemanticKITTI.py --test_area 20
python -B test_SemanticKITTI.py --test_area 21